import {test} from 'node:test';import assert from 'node:assert/strict';
import {parseRepository,observeRepository} from '../src/github.mjs';
const metadata={id:7,full_name:'owner/repo',private:false,default_branch:'main',description:'<script>hostile</script>',html_url:'https://github.com/owner/repo',archived:false,license:null};
const fetchOk=async(url)=>Response.json(String(url).includes('/commits/')?{sha:'a'.repeat(40)}:metadata);
test('accepts only GitHub owner/repository routes',()=>{assert.equal(parseRepository('https://github.com/owner/repo').fullName,'owner/repo');for(const v of ['https://evil.example/owner/repo','https://user:pass@github.com/owner/repo','owner/repo/extra','https://github.com/owner/repo?token=x'])assert.throws(()=>parseRepository(v))});
test('public snapshot pins revision and preserves licence absence',async()=>{const r=await observeRepository('owner/repo',{fetchImpl:fetchOk,now:()=>new Date('2026-10-07T00:00:00Z')});assert.equal(r.ok,true);assert.equal(r.node.revision,'a'.repeat(40));assert.equal(r.node.licence.standing,'unknown');assert.equal(r.node.summary,metadata.description);assert.equal(r.node.source.observedAt,'2026-10-07T00:00:00.000Z')});
test('rate limit is typed absence, not no findings',async()=>{const r=await observeRepository('owner/repo',{fetchImpl:async()=>new Response('',{status:403,headers:{'x-ratelimit-remaining':'0'}})});assert.equal(r.code,'rate_limited');assert.equal(r.ok,false)});
test('private responses and identity drift are refused',async()=>{for(const body of [{...metadata,private:true},{...metadata,full_name:'other/repo'}])assert.equal((await observeRepository('owner/repo',{fetchImpl:async()=>Response.json(body)})).ok,false)});
test('HTTP200 malformed metadata cannot become observed',async()=>{assert.equal((await observeRepository('owner/repo',{fetchImpl:async()=>Response.json({message:'broken'})})).code,'invalid_response')});
test('network error does not echo sensitive remote message',async()=>{const r=await observeRepository('owner/repo',{fetchImpl:async()=>{throw new Error('secret-token')}});assert.equal(r.code,'unreachable');assert.ok(!JSON.stringify(r).includes('secret-token'))});
test('redirects refused and requests stay credential-free',async()=>{const urls=[];await observeRepository('owner/repo',{fetchImpl:async(url,init)=>{urls.push(url);assert.equal(init.redirect,'error');assert.equal(init.headers.Authorization,undefined);return fetchOk(url)}});assert.equal(urls.length,2);assert.ok(urls.every(u=>u.startsWith('https://api.github.com/repos/owner/repo')))});

test('JSON with a non-JSON media type is refused',async()=>{const r=await observeRepository('owner/repo',{fetchImpl:async(url)=>String(url).includes('/commits/')?Response.json({sha:'a'.repeat(40)}):new Response(JSON.stringify(metadata),{headers:{'content-type':'text/html'}})});assert.equal(r.code,'invalid_response')});
