import {validateCosmic,projectCosmic,eventMolecules,descendants} from './cosmic.mjs';
import {resolveEntry} from './entry.mjs';
const $=id=>document.getElementById(id),el=(tag,className='',value='')=>{const n=document.createElement(tag);n.className=className;n.textContent=value;return n;};
async function start(){
let packet;try{const response=await fetch('./data/cosmic-fixture.json');if(!response.ok)throw new Error('Fixture unavailable');packet=validateCosmic(await response.json());}catch{ $('cosmic-scene').append(el('p','caption','Source packet rejected or unavailable. No partial event history was accepted.'));$('matter-inspector').textContent='Source unavailable. Return to the hub to choose another path.';$('epoch').disabled=true;$('sandbox-entry').disabled=true;return;}
const epochs=[...new Set(packet.events.flatMap(e=>[e.occurredAt,e.recordedAt]))].sort((a,b)=>Date.parse(a)-Date.parse(b));
let selected='universe',focus='universe',history=[],list=false,projection;
$('epoch').max=epochs.length-1;$('epoch').value=epochs.length-1;
const button=(label,fn,className='inspector-link')=>{const b=el('button',className,label);b.addEventListener('click',fn);return b;};
function choose(id){selected=id;render();}
function descend(id){history.push({focus,selected,epoch:$('epoch').value,known:$('known-then').checked});history=history.slice(-100);focus=id;selected=id;render();}
function positions(nodes){const out=new Map();if(focus==='universe'){out.set('universe',[50,8]);
 const galaxies=nodes.filter(b=>b.kind==='galaxy');galaxies.forEach((g,i)=>{const x=20+i*30,y=26+(i%2)*8;out.set(g.id,[x,y]);const children=projection.relationships.filter(r=>r.kind==='contains'&&r.from===g.id).map(r=>nodes.find(b=>b.id===r.to)).filter(Boolean);children.forEach((s,j)=>{const sx=x+(j===0?-9:9),sy=y+22;out.set(s.id,[sx,sy]);const planets=projection.relationships.filter(r=>r.kind==='contains'&&r.from===s.id).map(r=>nodes.find(b=>b.id===r.to)).filter(Boolean);planets.forEach((p,k)=>{if(!out.has(p.id))out.set(p.id,[sx+(k%2===0?-5:5),sy+19+Math.floor(k/2)*12]);});});});
 const missing=nodes.filter(n=>n.id!=='universe'&&!out.has(n.id));missing.forEach((n,i)=>out.set(n.id,[12+(i%7)*12,90-Math.floor(i/7)*10]));
 }else{const rest=nodes.filter(b=>b.id!==focus);out.set(focus,[50,45]);rest.forEach((b,i)=>{const a=i/Math.max(1,rest.length)*Math.PI*2-Math.PI/2;out.set(b.id,[50+Math.cos(a)*35,48+Math.sin(a)*31]);});}return out;}
function drawScene(){const host=$('cosmic-scene');host.replaceChildren();const ids=new Set(descendants(projection,focus));const direct=new Set(projection.relationships.filter(r=>r.kind==='contains'&&r.from===focus).map(r=>r.to));const narrow=matchMedia('(max-width:600px)').matches;const nodes=projection.bodies.filter(b=>ids.has(b.id)&&(!narrow||b.id===focus||direct.has(b.id)));const points=positions(nodes);const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('field-svg');svg.setAttribute('viewBox','0 0 100 100');svg.setAttribute('preserveAspectRatio','none');svg.setAttribute('aria-hidden','true');
 for(const r of projection.relationships.filter(r=>r.kind==='contains')){const a=points.get(r.from),b=points.get(r.to);if(!a||!b)continue;const line=document.createElementNS(svg.namespaceURI,'line');for(const [key,value] of Object.entries({x1:a[0],y1:a[1],x2:b[0],y2:b[1],stroke:'#668fa555','stroke-width':'.12'}))line.setAttribute(key,String(value));svg.append(line);}host.append(svg);
 const atomPoints=new Map();for(const n of nodes){const point=points.get(n.id);if(!point)continue;const b=button(n.label,()=>choose(n.id),'body-button');b.dataset.kind=n.kind;b.dataset.active=n.active;b.dataset.body=n.id;b.style.left=point[0]+'%';b.style.top=point[1]+'%';b.setAttribute('aria-label',`Inspect ${n.label}`);b.setAttribute('aria-pressed',String(selected===n.id));b.prepend(el('span','sphere'));host.append(b);
 const atoms=projection.atoms.filter(e=>e.subject===n.id);atoms.forEach((e,i)=>{const angle=i/Math.max(1,atoms.length)*Math.PI*2+.6;const atom=button('',()=>choose(e.id),'atom');const ap=[point[0]+Math.cos(angle)*4,point[1]+Math.sin(angle)*6];atomPoints.set(e.id,ap);atom.style.left=ap[0]+'%';atom.style.top=ap[1]+'%';atom.setAttribute('aria-label',`Inspect event ${e.id}`);atom.title=e.type;host.append(atom);});}
 for(const r of projection.relationships.filter(r=>r.kind==='bond')){const a=atomPoints.get(r.from),b=atomPoints.get(r.to);if(!a||!b)continue;const line=document.createElementNS(svg.namespaceURI,'line');for(const [key,value] of Object.entries({x1:a[0],y1:a[1],x2:b[0],y2:b[1],stroke:'#8ce4ca','stroke-width':'.22','stroke-dasharray':'1 .7'}))line.setAttribute(key,String(value));svg.append(line);}
}
function inspector(){const host=$('matter-inspector');host.replaceChildren();const atom=projection.atoms.find(e=>e.id===selected),body=projection.bodies.find(b=>b.id===selected);
 if(!atom&&!body){selected=focus;return inspector();}
 host.append(el('p','eyebrow',atom?'EVENT / ATOM':'IDENTITY / BODY'),el('h2','',atom?atom.type:body.label),el('p','tag',atom?'SYNTHETIC EVENT':body.active?'FIXTURE ACTIVITY OBSERVED':'DECLARED · NO VISIBLE EVENTS'));
 const fields=atom?[['Event identity',atom.id],['Subject',atom.subject],['Actor',atom.actor],['Occurred',atom.occurredAt],['Recorded',atom.recordedAt],['Source',atom.source],['Standing',atom.standing]]:[['Identity',body.id],['Scale',body.kind],['Source',body.source],['Visible event atoms',String(body.eventIds.length)]];
 const dl=el('dl','evidence-dl');for(const [k,v] of fields)dl.append(el('dt','',k),el('dd','',v));host.append(dl);
 if(atom){host.append(button('Return to subject →',()=>choose(atom.subject)));const bonds=projection.relationships.filter(r=>r.kind==='bond'&&(r.from===atom.id||r.to===atom.id));host.append(el('h3','','EXPLICIT BONDS'));for(const r of bonds)host.append(button(`${r.id} → ${r.from===atom.id?r.to:r.from}`,()=>choose(r.from===atom.id?r.to:r.from)));if(!bonds.length)host.append(el('p','','No explicit bonds in this packet. Nearby time is not evidence of causation.'));}
 else{if(body.id!==focus)host.append(button('Descend into '+body.label,()=>descend(body.id)));host.append(el('h3','','RECIPROCAL STRUCTURE'));for(const r of projection.relationships.filter(r=>r.kind==='contains'&&(r.from===body.id||r.to===body.id))){const target=r.from===body.id?r.to:r.from;host.append(button(`${r.from===body.id?'↘ Child':'↗ Parent'} · ${projection.bodies.find(b=>b.id===target).label}`,()=>choose(target)));}host.append(el('h3','','SOURCE EVENTS'));for(const id of body.eventIds)host.append(button(id,()=>choose(id)));}
 host.append(el('h3','','EVIDENCE BOUNDARY'),el('p','','This synthetic packet illustrates the design. The map owns geometry only; it grants no authority and claims no live agent runtime. A1-A1 remains provisional and perspective-dependent.'));
}
function render(){const at=epochs[Number($('epoch').value)],knownAt=$('known-then').checked?at:epochs.at(-1);projection=projectCosmic(packet,{at,knownAt});$('epoch-label').textContent=new Date(at).toISOString().slice(11,16)+' UTC';$('matter-count').textContent=`${projection.atoms.length} atoms · ${eventMolecules(projection).length} molecules`;$('focus-label').textContent=projection.bodies.find(b=>b.id===focus).label;$('cosmic-back').disabled=!history.length;$('cosmic-scene').hidden=list;$('matter-list').hidden=!list;$('list-toggle').setAttribute('aria-pressed',String(list));drawScene();
 const host=$('matter-list');host.replaceChildren();for(const e of projection.atoms){const b=button(e.type,()=>choose(e.id),'event-row');b.append(el('small','',`${e.id} · ${e.subject} · occurred ${e.occurredAt.slice(11,16)} · recorded ${e.recordedAt.slice(11,16)}`));host.append(b);}if(!projection.atoms.length)host.append(el('p','','No visible events within this replay coordinate. This does not establish non-occurrence.'));inspector();}
$('epoch').addEventListener('input',render);$('known-then').addEventListener('change',render);$('list-toggle').addEventListener('click',()=>{list=!list;render();});$('cosmic-root').addEventListener('click',()=>descend('universe'));$('cosmic-back').addEventListener('click',()=>{const previous=history.pop();if(!previous)return;({focus,selected}=previous);$('epoch').value=previous.epoch;$('known-then').checked=previous.known;render();});
$('sandbox-entry').addEventListener('click',()=>{const r=resolveEntry({contract:'environment-entry/v0',id:'bounded-world',mode:'sandbox',destination:'/cosmic.html'});$('entry-result').textContent=`${r.code}: an owning server must verify identity, scope, expiry and admission before a sandbox session can begin. No session was created.`;});render();

matchMedia('(max-width:600px)').addEventListener('change',render);

}
start();
