import {createRun,act,replay,PLACES,RULES} from './v1-engine.mjs';
const $=id=>document.getElementById(id),make=(tag,text='',className='')=>{const n=document.createElement(tag);n.textContent=text;n.className=className;return n;};
const storageKey='htc-v1-local';let run=null,request=0;
const say=text=>{$('status').textContent=text;};
function clearSave(){try{localStorage.removeItem(storageKey);}catch{say('Device storage unavailable. No removal could be verified.');return false;}return true;}
function save(){if(!$('remember').checked)return true;try{localStorage.setItem(storageKey,JSON.stringify({events:run.events}));return true;}catch{say('Device save failed. This fixture remains in memory; export it before leaving.');return false;}}
function action(kind,extra={}){const result=act(run,{kind,...extra,expectedRevision:run.revision,key:'ui:'+run.revision+':'+(++request)});if(!result.ok){say('Action refused: '+result.reason+'. State and rewards unchanged.');return;}run=result.run;render();say('Accepted '+kind+' · event '+result.event.id+' · replay revision '+run.revision);save();}
function render(){const active=!!run;$('creation').hidden=active;$('play').hidden=!active;if(!active)return;
 const state=run.state;const map=$('place-map');map.replaceChildren();for(const [id,place] of Object.entries(PLACES)){const b=make('button',place.label);b.dataset.place=id;b.disabled=id===state.place||!PLACES[state.place].neighbours.includes(id);if(id===state.place)b.setAttribute('aria-current','location');b.addEventListener('click',()=>action('move',{place:id}));map.append(b);}
 $('place-label').textContent='LOCAL SCENE / '+state.place.toUpperCase();$('scene-title').textContent=PLACES[state.place].label;document.querySelector('.scene').dataset.place=state.place;$('avatar').dataset.appearance=state.character.appearance;
 $('scene-description').textContent=state.place==='camp'?'Choose a path to the training ground or forge.':state.place==='training'?'Practice twice to learn enough to craft a focus. Six accepted practices are available in this fixture.':'A focus requires two ore, one fuel and two practices. A spark requires a focus and one essence.';
 const sheet=$('character-sheet');sheet.replaceChildren(make('h2',state.character.name),make('p',state.character.appearance+' · '+state.character.id,'muted'));const dl=make('dl');for(const [label,value] of [['Practice',state.practice+'/'+RULES.practiceLimit],['Ore',state.inventory.ore],['Fuel',state.inventory.fuel],['Essence',state.inventory.essence],['Focus',state.inventory.focus]])dl.append(make('dt',label),make('dd',String(value)));sheet.append(dl,make('p','Spark casts: '+state.spellsCast),make('p','Revision '+run.revision+' · '+run.rulesVersion,'muted'));
 const actions=$('world-actions');actions.replaceChildren();for(const [kind,label,extra] of [['practice','Practise',{}],['craft','Forge focus',{recipe:'focus'}],['cast','Cast spark',{ability:'spark'}]]){const b=make('button',label);b.dataset.action=kind;b.disabled=(kind==='practice'&&state.place!=='training')||(kind==='craft'&&state.place!=='forge');b.addEventListener('click',()=>action(kind,extra));actions.append(b);}
 const events=$('event-history');events.replaceChildren();for(const event of run.events.slice(-50))events.append(make('li',event.id+' · '+event.action.kind+' · revision '+event.revision));
}
$('character-form').addEventListener('submit',event=>{event.preventDefault();try{run=createRun({name:$('character-name').value,appearance:$('appearance').value,seed:'v1-public-fixture'});request=0;render();say('Entered local V1. No server session or external permission was created.');save();}catch(e){say('Character refused: '+e.message);}});
$('remember').addEventListener('change',()=>{if($('remember').checked&&run)save();else if(!$('remember').checked&&clearSave())say('Device save removed. Current fixture remains in memory only.');});
$('leave-v1').addEventListener('click',()=>{const removed=clearSave();run=null;render();if(removed)say('Left local V1. Device save removed; no server session existed.');});
$('export-run').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({contract:'v1-local-export/1',standing:run.standing,events:run.events},null,2)],{type:'application/json'}));const a=make('a');a.href=url;a.download='v1-local-events.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);say('Exported local fixture events. This file grants no identity or permission outside V1.');});
try{const saved=localStorage.getItem(storageKey);if(saved){if(saved.length>200000)throw new Error('Saved fixture too large');run=replay(JSON.parse(saved).events);$('remember').checked=true;render();say('Restored device fixture by replay. No server or external authority is implied.');}}catch{run=null;say('Saved fixture rejected or storage unavailable. No partial history was accepted. Create a new fixture or clear the device save.');}
