/** Newly authored public local fixture. No hosted admission, account or Atlas authority. */
export const RULES = Object.freeze({version:'v1-local-rules/1',practiceLimit:6,eventLimit:500});
export const PLACES = freeze({camp:{label:'Camp',neighbours:['training','forge']},training:{label:'Training ground',neighbours:['camp']},forge:{label:'Forge',neighbours:['camp']}});
const VERSION='v1-local-run/1';
const appearances=['ember','tide','moss'];
function freeze(value){if(value&&typeof value==='object'){Object.values(value).forEach(freeze);Object.freeze(value);}return value;}
function text(value,max=80){return typeof value==='string'&&value.trim().length>0&&value.length<=max&&!/[\u0000-\u001f\u007f]/.test(value);}
function hash(value){let n=2166136261;for(const c of value){n=Math.imul(n^c.charCodeAt(0),16777619)>>>0;}return n.toString(16).padStart(8,'0');}
function same(a,b){return JSON.stringify(a)===JSON.stringify(b);}
function refuse(run,reason){return {ok:false,reason,run,grantsAuthority:false};}
function normalize(action){if(!action||typeof action!=='object'||Array.isArray(action))throw Error('invalid_action');switch(action.kind){case 'move':if(!Object.hasOwn(PLACES,action.place))throw Error('unknown_place');return {kind:'move',place:action.place};case 'practice':return {kind:'practice'};case 'craft':if(action.recipe!=='focus')throw Error('unknown_recipe');return {kind:'craft',recipe:'focus'};case 'cast':if(action.ability!=='spark')throw Error('unknown_ability');return {kind:'cast',ability:'spark'};default:throw Error('unknown_action');}}
function transition(prior,action){const state=structuredClone(prior);switch(action.kind){case 'move':if(!PLACES[state.place].neighbours.includes(action.place))throw Error('unreachable_place');state.place=action.place;break;case 'practice':if(state.place!=='training')throw Error('wrong_place');if(state.practice>=RULES.practiceLimit)throw Error('practice_limit');state.practice++;break;case 'craft':if(state.place!=='forge')throw Error('wrong_place');if(state.practice<2)throw Error('practice_required');if(state.inventory.ore<2||state.inventory.fuel<1)throw Error('insufficient_resources');if(state.inventory.focus)throw Error('focus_already_owned');state.inventory.ore-=2;state.inventory.fuel--;state.inventory.focus++;break;case 'cast':if(!state.inventory.focus)throw Error('focus_required');if(state.inventory.essence<1)throw Error('insufficient_resources');state.inventory.essence--;state.spellsCast++;break;}return state;}
function initial(action){if(!text(action.name,40)||!text(action.seed,80)||!appearances.includes(action.appearance))throw Error('invalid_character');const name=action.name.trim();return {character:{id:`local-character-${hash(JSON.stringify([name,action.appearance,action.seed]))}`,name,appearance:action.appearance},place:'camp',inventory:{ore:3,fuel:3,essence:3,focus:0},practice:0,spellsCast:0};}
function wrap(events,state){return freeze({version:VERSION,standing:'local-synthetic-fixture',rulesVersion:RULES.version,revision:events.length-1,events,state,grantsAuthority:false});}
export function createRun({name,appearance='ember',seed='local-first'}={}){const action={kind:'create',name,appearance,seed};const state=initial(action);const event={id:'local-event-0',revision:0,key:'create',rulesVersion:RULES.version,action,outcome:state};return wrap([event],state);}
/** Validate history by recomputing every accepted rule outcome; snapshots are never trusted. */
export function replay(events){if(!Array.isArray(events)||events.length<1||events.length>RULES.eventLimit)throw Error('invalid_history');const copied=structuredClone(events);const keys=new Set();let state;for(let i=0;i<copied.length;i++){const event=copied[i];if(!event||event.id!==`local-event-${i}`||event.revision!==i||event.rulesVersion!==RULES.version||!text(event.key,100)||keys.has(event.key))throw Error('invalid_event');keys.add(event.key);if(i===0){if(event.key!=='create'||event.action?.kind!=='create')throw Error('creation_required');state=initial(event.action);}else{const action=normalize(event.action);if(!same(action,event.action))throw Error('noncanonical_action');state=transition(state,action);}if(!same(event.outcome,state))throw Error('outcome_divergence');}return wrap(copied,state);}
/** Accepted events append once; refusals preserve the caller's run and award nothing. */
export function act(run,request){let verified,action;try{if(run?.version!==VERSION)throw Error('invalid_run');verified=replay(run.events);if(!same(verified,run))throw Error('snapshot_divergence');if(!request||!text(request.key,100))throw Error('invalid_key');action=normalize(request);}catch(error){return refuse(run,error.message);}const previous=verified.events.find(event=>event.key===request.key);if(previous){return same(previous.action,action)?{ok:true,run:verified,event:previous,replayed:true,grantsAuthority:false}:refuse(run,'key_conflict');}if(!Number.isSafeInteger(request.expectedRevision)||request.expectedRevision!==verified.revision)return refuse(run,'stale_revision');if(verified.events.length>=RULES.eventLimit)return refuse(run,'event_limit');let outcome;try{outcome=transition(verified.state,action);}catch(error){return refuse(run,error.message);}const revision=verified.revision+1;const event={id:`local-event-${revision}`,revision,key:request.key,rulesVersion:RULES.version,action,outcome};return {ok:true,run:wrap([...verified.events,event],outcome),event:freeze(event),replayed:false,grantsAuthority:false};}
